"""add_sync_config_and_history_tables

Revision ID: ec97950b2c4e
Revises: 3c0400dfe565
Create Date: 2026-01-24 01:16:31.252605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec97950b2c4e'
down_revision: Union[str, None] = '3c0400dfe565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('sync_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('is_auto_sync_enabled', sa.Boolean(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sa.String(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('rows_cached', sa.Integer(), nullable=True),
    sa.Column('tables_cached', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['db_connections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id')
    )
    op.create_index(op.f('ix_sync_configs_id'), 'sync_configs', ['id'], unique=False)
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('chat_messages', 'sql_query',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_chat_messages_conversation_id'), table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.drop_constraint(op.f('chat_messages_conversation_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'conversations', ['conversation_id'], ['id'])
    op.drop_index(op.f('idx_conversations_user_id'), table_name='conversations')
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.drop_constraint(op.f('conversations_user_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'])
    op.alter_column('dashboards', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.drop_index(op.f('idx_dashboards_user_id'), table_name='dashboards')
    op.create_index(op.f('ix_dashboards_id'), 'dashboards', ['id'], unique=False)
    op.drop_constraint(op.f('dashboards_user_id_fkey'), 'dashboards', type_='foreignkey')
    op.create_foreign_key(None, 'dashboards', 'users', ['user_id'], ['id'])
    op.drop_column('db_connections', 'config_encrypted')
    op.add_column('sync_history', sa.Column('sync_config_id', sa.Integer(), nullable=True))
    op.add_column('sync_history', sa.Column('connection_id', sa.Integer(), nullable=True))
    op.add_column('sync_history', sa.Column('tables_synced', sa.JSON(), nullable=True))
    op.add_column('sync_history', sa.Column('is_incremental', sa.Boolean(), nullable=True))
    op.add_column('sync_history', sa.Column('duration_seconds', sa.Float(), nullable=True))
    op.alter_column('sync_history', 'error_message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_sync_history_source'), table_name='sync_history')
    op.drop_index(op.f('idx_sync_history_user_id'), table_name='sync_history')
    op.create_index(op.f('ix_sync_history_id'), 'sync_history', ['id'], unique=False)
    op.drop_constraint(op.f('sync_history_user_id_fkey'), 'sync_history', type_='foreignkey')
    op.create_foreign_key(None, 'sync_history', 'sync_configs', ['sync_config_id'], ['id'])
    op.create_foreign_key(None, 'sync_history', 'db_connections', ['connection_id'], ['id'])
    op.drop_column('sync_history', 'retry_count')
    op.drop_column('sync_history', 'created_at')
    op.drop_column('sync_history', 'user_id')
    op.drop_column('sync_history', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_history', sa.Column('source', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('sync_history', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sync_history', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('sync_history', sa.Column('retry_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sync_history', type_='foreignkey')
    op.drop_constraint(None, 'sync_history', type_='foreignkey')
    op.create_foreign_key(op.f('sync_history_user_id_fkey'), 'sync_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_sync_history_id'), table_name='sync_history')
    op.create_index(op.f('idx_sync_history_user_id'), 'sync_history', ['user_id'], unique=False)
    op.create_index(op.f('idx_sync_history_source'), 'sync_history', ['source'], unique=False)
    op.alter_column('sync_history', 'error_message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('sync_history', 'duration_seconds')
    op.drop_column('sync_history', 'is_incremental')
    op.drop_column('sync_history', 'tables_synced')
    op.drop_column('sync_history', 'connection_id')
    op.drop_column('sync_history', 'sync_config_id')
    op.add_column('db_connections', sa.Column('config_encrypted', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('db_connections', 'port',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('db_connections', 'host',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'dashboards', type_='foreignkey')
    op.create_foreign_key(op.f('dashboards_user_id_fkey'), 'dashboards', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_dashboards_id'), table_name='dashboards')
    op.create_index(op.f('idx_dashboards_user_id'), 'dashboards', ['user_id'], unique=False)
    op.alter_column('dashboards', 'config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_user_id_fkey'), 'conversations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.create_index(op.f('idx_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_conversation_id_fkey'), 'chat_messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.create_index(op.f('idx_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.alter_column('chat_messages', 'sql_query',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('chat_messages', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_sync_configs_id'), table_name='sync_configs')
    op.drop_table('sync_configs')
    # ### end Alembic commands ###
